name: akismet
version: 0.2.0
author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using Akismet service (https://akismet.com).
homepage: https://github.com/cedx/akismet.dart
documentation: http://cedx.github.io/akismet.dart/api
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http: '>=0.9.0 <0.10.0'
dev_dependencies:
  args: '>=0.9.0 <0.10.0'
  browser: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
