author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using Akismet service.
documentation: http://dev.belin.io/akismet.dart/api
homepage: https://github.com/cedx/akismet.dart
name: akismet
version: 0.2.1

dependencies:
  args: '>=0.10.0 <0.13.0'
  http: '>=0.10.0 <0.12.0'
  http_server: '>=0.9.0 <0.10.0'
  path: '>=1.0.0 <2.0.0'
  route: '>=0.4.6 <0.5.0'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  unittest: '>=0.11.0 <0.12.0'

environment:
  sdk: '>=1.0.0 <2.0.0'
