name: akismet
version: 0.2.1
author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using Akismet service (https://akismet.com).
homepage: http://akismet.belin.io
documentation: http://akismet.belin.io/api
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.10.0'
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <0.10.0'
  route: '>=0.4.6 <0.5.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
